services:
  mssql:
    container_name: mssql_container
    image: mssql
    environment:
      MSSQL_USER: user
      MSSQL_PASSWORD: Adekunle1993$
      PGDATA: /data/mssql
      volumes:
        -mssql:/data/mssql
      ports:
        - "1433:1433"
      networks:
        mssql
      restart: unless-stopped
      pgadmin:
        container_name:pgadmin_container
      image: dpage/pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'false'
        volumes: -pgadmin:/var/lib/pgadmin
        ports: -"5050:80"
        networks: -mssql
        restart: unless-stopped

      network:
        mssql:
          driver: bridge

      volume:
        mssql:
          pgadmin: